name: mvn site

on:
  workflow_dispatch:

jobs:
  release:

    name: Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: maven
      - name: Generate website
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          mvn install
          mvn site:site site:stage scm-publish:publish-scm
